#!/usr/bin/env python3
"""
Build data/diagrams.js from data/diagrams/*.svg + data/diagrams/descriptions.json.

The web app runs from file:// (no server), so it cannot fetch() individual
SVG files at runtime. This script bundles the .svg files into a single JS
manifest assigned to window.TOGAF_DIAGRAMS:

    window.TOGAF_DIAGRAMS = {
      diagrams: [
        { id, title, topic, description, svg: "<svg>...</svg>", buildHook? },
        ...
      ]
    };

Re-run after editing any .svg file or descriptions.json:
    python build_diagrams.py
"""

import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
DIAGRAM_DIR = os.path.join(HERE, "data", "diagrams")
OUT_PATH = os.path.join(HERE, "data", "diagrams.js")
DESC_PATH = os.path.join(DIAGRAM_DIR, "descriptions.json")


def main():
    with open(DESC_PATH, "r", encoding="utf-8") as f:
        desc_doc = json.load(f)

    bundled = []
    for entry in desc_doc["diagrams"]:
        svg_path = os.path.join(DIAGRAM_DIR, entry["id"] + ".svg")
        if not os.path.exists(svg_path):
            sys.exit(f"Missing SVG file: {svg_path}")
        with open(svg_path, "r", encoding="utf-8") as f:
            svg = f.read().strip()
        bundled.append({
            "id": entry["id"],
            "title": entry["title"],
            "topic": entry.get("topic", ""),
            "description": entry["description"],
            "svg": svg,
            **({"buildHook": entry["buildHook"]} if "buildHook" in entry else {}),
        })

    payload = {"diagrams": bundled, "count": len(bundled)}
    with open(OUT_PATH, "w", encoding="utf-8") as f:
        f.write("/* Auto-generated by build_diagrams.py — do not edit by hand.\n")
        f.write("   Source of truth: data/diagrams/*.svg + descriptions.json. */\n")
        f.write("window.TOGAF_DIAGRAMS = ")
        json.dump(payload, f, ensure_ascii=False, indent=2)
        f.write(";\n")

    print(f"Bundled {len(bundled)} diagrams → {OUT_PATH}")


if __name__ == "__main__":
    main()
